version: '3'
services: 
    nginx:
        image: nginx:latest
        container_name: guggenheim_nginx
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./htpasswd:/etc/nginx/htpasswd
            - ./logs:/var/logs/nginx
        ports:
            - 80:80
            - 443:443
    node:
        build: .
        environment:
            - NODE_ENV=production
            - TZ=America/New_York
            - MQTT_BROKER=localhost
            - SERVER_ADDR=localhost
        command:
            sh -c "ln -snf /usr/share/zoneinfo/$${TZ} /etc/localtime &&
            echo America/$${TZ} > /etc/timezone &&
            npm run dev"
        volumes:
            - .:/home/node/app
        ports:
            - "3001:3001"
            - "3002:3002"
        stdin_open: true
        tty: true
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
    node-red:
        image: nodered/node-red
        volumes:
            - ./node-red-data:/data
            - ./node-red-dev:/node-dev
        ports:
            - "1880:1880"
        stdin_open: true
        tty: true
    mosquitto:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "8883:8883"
        volumes:
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/logs:/mosquitto/logs
            - ./mosquitto/config:/mosquitto/config